from typing import Literal
from langchain_core.messages import AIMessage, ToolMessage
from langgraph.graph import START, END, StateGraph, MessagesState
from chains import revisor, first_responder
from tool_executor import execute_tools

# Define the maximum number of revision loops we allow the agent to make.
# This prevents infinite loops where the LLM keeps researching forever.
MAX_ITERATIONS = 2

def draft_node(state: MessagesState):
    """
    Node 1: Draft the initial response.
    Takes the current conversation state, passes it to the first_responder chain,
    and returns the LLM's drafted response (which includes search queries).
    """
    # Invoke the drafter chain with the current list of messages
    response = first_responder.invoke({"messages": state["messages"]})
    # Return the new message to be appended to the global state
    return {"messages": [response]}

def revise_node(state: MessagesState):
    """
    Node 3: Revise the answer based on tool results.
    Takes the conversation state (which now includes Tavily search results),
    passes it to the revisor chain, and returns the updated draft.
    """
    # Invoke the revisor chain to generate a better answer with citations
    response = revisor.invoke({"messages": state["messages"]}) 
    return {"messages": [response]}

def event_loop(state: MessagesState) -> Literal["execute_tools", "END"]:
    """
    Conditional Edge: Determine whether to continue researching or end the graph.
    It counts how many times tools have been executed to enforce the MAX_ITERATIONS limit.
    """
    # Count how many ToolMessages exist in the state history.
    # Each time execute_tools runs, it adds ToolMessages to the state.
    count_tools_visit = sum(
        isinstance(item, ToolMessage) for item in state["messages"]
    )
    
    num_iterations = count_tools_visit
    
    # If we have hit our iteration limit, route the graph to the END node.
    if num_iterations >= MAX_ITERATIONS:
        return END
        
    # Otherwise, route the graph back to the execute_tools node to run the new search queries.
    return "execute_tools"

# ---------------------------------------------------------
# GRAPH CONSTRUCTION
# ---------------------------------------------------------
# Initialize a StateGraph using the built-in MessagesState (which is just a list of messages)
builder = StateGraph(MessagesState)

# Add our three main logic nodes to the graph
builder.add_node("draft", draft_node)             # Generates first draft + search queries
builder.add_node("execute_tools", execute_tools)  # Runs the search queries via Tavily
builder.add_node("revise", revise_node)           # Generates a revised draft based on search results

# Define the exact flow/edges of the graph
builder.add_edge(START, "draft")                  # Start -> Draft Node
builder.add_edge("draft", "execute_tools")        # Draft Node -> Tool Executor Node
builder.add_edge("execute_tools", "revise")       # Tool Executor Node -> Revise Node

# The Revise node doesn't have a static next step. It uses the event_loop function 
# to dynamically decide whether to loop back to "execute_tools" or stop at "END".
builder.add_conditional_edges("revise", event_loop, ["execute_tools", END])

# Compile the graph into a runnable application
graph = builder.compile()

# Optional: Print a mermaid.js representation of the graph architecture
print(graph.get_graph().draw_mermaid())

# ---------------------------------------------------------
# GRAPH EXECUTION
# ---------------------------------------------------------
# Kick off the graph with the initial user prompt
res = graph.invoke({
    "messages": [
        {
            "role": "user",
            "content": "Write about AI-Powered SOC/ autonomous soc problem domain, list startups that do that and raised capital."
        }
    ]
})

# ---------------------------------------------------------
# PARSING THE FINAL OUTPUT
# ---------------------------------------------------------
# Grab the very last message generated by the graph (which should be from the 'revise' node)
last_message = res["messages"][-1]

# Because we used bind_tools, the actual text is hidden inside the tool_calls dictionary,
# rather than in the standard 'content' field. We extract and print it here.
if isinstance(last_message, AIMessage) and last_message.tool_calls:
    print(last_message.tool_calls[0]["args"]["answer"])

# Print the entire raw state history for debugging
print(res)