import os
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from operator import itemgetter
from dotenv import load_dotenv
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_pinecone import PineconeVectorStore
from langchain_core.messages import HumanMessage
from langchain_core.prompts import ChatPromptTemplate

load_dotenv()

print("Initializing Components...")

embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")
llm = ChatGoogleGenerativeAI(
     model="gemini-2.5-flash",
     temperature=0
)
vector_store = PineconeVectorStore(
    index_name=os.getenv("INDEX_NAME"),
    embedding=embeddings
)
retriever = vector_store.as_retriever(search_kwargs={"k": 3})

prompt_template = ChatPromptTemplate.from_template(
    """Answer the question based on the following context:
    
    {context}
    
    Question: {question}
    
    Provide a detailed answer:
    """
)

def format_docs(docs):
    """Format retrieved documents into a single string."""  
    return "\n\n".join(doc.page_content for doc in docs)

def retrieval_chain_without_lcel(query):
    """
    Simple retrieval chain without LCEL.
    Manually retrieves documents, formats them, and generates a response.
    
    Limitations:
    -Manual step by step execution
    -No built-in streaming support
    -No async support without external code
    -Harder to compose with other chains or tools
    -More verbose and error-prone
    """
    #Step 1: Retrieve relevant documents
    docs = retriever.invoke(query) #Invokes the retriever with the query to fetch relevant documents from the vector store. The retriever uses the embeddings to find documents that are semantically similar to the query, returning a list of Document objects that contain the text content and metadata of the retrieved documents.
    
    #Step 2: Format the retrieved documents into a single string
    context = format_docs(docs) #Creates a single string that combines the content of all retrieved documents. This formatted context will be used as input to the LLM to provide relevant information for answering the query.
    
    #Step 3: Create a prompt with the context and the original query
    messages = prompt_template.format_messages(context=context, question=query) # Generates a list of messages that will be sent to the LLM. The prompt template is filled with the formatted context and the original query, creating a structured input that guides the LLM in generating a relevant and detailed response.
    
    #Step 4: Invoke the LLM with the formatted prompt to generate a response
    response = llm.invoke(messages) #Invokes the LLM with the structured messages to generate a response. The LLM processes the input, taking into account the context provided by the retrieved documents and the original query, and produces a detailed answer based on its understanding of the information.
    
    #Step 5: Return the generated response
    return response.content

def retrieval_chain_with_lcel():
    """
    Creates a retrieval chain using LCEL (LangChain Expression Language).
    Returns a chain that can be invoked with {"question":"...."}
    
    Advantages over non_LCEL approach:
    -Declarative and composable: Easy to chain operations with pipe operator (|)
    -Built-in streaming support: chain.stream() works out of the box
    -Built-in async support: chain.ainvoke() and chain.astream() available
    -Batch processing: chain.batch() and chain.abatch() for multiple inputs
    -Type safety: Better integration with Langchain's type system
    -Less code: More concise and readable
    -Reusable:Chain can be saved, shared, and composed with other chains
    -Better debugging: LangChain provides better observability and debugging tools.
    """
    retrieval_chain = (
        RunnablePassthrough.assign(
            context = itemgetter("question") | retriever | format_docs #assigns context and keeps question unchanged for later use in the prompt. The context is generated by retrieving relevant documents based on the question and formatting them into a single string.
        )
        |
        prompt_template |
        llm |
        StrOutputParser()
    )
    
    return retrieval_chain
    
    

if __name__ == "__main__":
    print("Retrieving documents... ")
    
    #Query
    query = "What is Pinecone in machine learning?"
    
    #Option 0 (No RAG)
    print("\n" + "="*70)
    print("IMPLEMENTATION 0: Raw LLM Invocation (No RAG)")
    print("="*70)
    result_raw = llm.invoke([HumanMessage(content=query)]) #Without RAG, we directly invoke the LLM with the query. 
    #The LLM generates a response based solely on its pre-trained knowledge, without any external context or documents.
    print("\nAnswer:")
    print(result_raw.content)
    
    #Option 1 (RAG without LCEL)
    print("\n" + "="*70)
    print("IMPLEMENTATION 1: RAG without LCEL")
    print("="*70)
    result_without_lcel = retrieval_chain_without_lcel(query)
    print("\nAnswer:")
    print(result_without_lcel)
    
    #Option 2 (RAG with LCEL(Langchain Expression Language))
    print("\n" + "="*70)
    print("IMPLEMENTATION 2: RAG with LCEL (better approach)")
    print("="*70)
    print("Why lcel is better:")
    print("-More concise and declarative")
    print("-Built-in streaming support: chain.stream()")
    print("-Built-in async support: chain.ainvoke()")
    print("-Easy to compose with other chains or tools")
    print("-Better for production use")
    print("="*70)
    chain_with_lcel = retrieval_chain_with_lcel()
    result_with_lcel = chain_with_lcel.invoke({"question": query})
    print("\nAnswer:")
    print(result_with_lcel)