from dotenv import load_dotenv

from schemas import AnswerQuestion, ReviseAnswer

# Load environment variables (like TAVILY_API_KEY) from the .env file
load_dotenv()

from langchain_tavily import TavilySearch
from langchain_core.tools import StructuredTool
from langgraph.prebuilt import ToolNode

# Initialize the Tavily search tool, limiting it to 5 results per query to save tokens/context space
tavily_tool = TavilySearch(max_results=5)

def run_queries(search_queries: list[str], **kwargs):
    """
    This function takes the list of search queries generated by the LLM
    and executes them against the Tavily search engine.
    """
    # We use .batch() to run multiple search queries concurrently, speeding up the process
    return tavily_tool.batch([{"query": query} for query in search_queries])


# ToolNode is a specialized LangGraph node that automatically handles tool execution.
# It looks at the last AI message, checks if the LLM requested a tool, runs the tool, 
# and appends the result as a ToolMessage to the state.
execute_tools = ToolNode(
    [
        # We create a StructuredTool that maps the 'AnswerQuestion' tool call to our run_queries function.
        # This handles the searches requested during the FIRST draft.
        StructuredTool.from_function(run_queries, name=AnswerQuestion.__name__),
        
        # We create another StructuredTool that maps the 'ReviseAnswer' tool call to our run_queries function.
        # This handles the searches requested during the REVISION drafts.
        StructuredTool.from_function(run_queries, name=ReviseAnswer.__name__),
    ]
)